# docker-compose.yml
version: '2'

services:

  plexrequests:
    image: linuxserver/plexrequests
    container_name: plexrequests
    ports:
      - "3000:3000"
    environment:
      - PUID=1010
      - PGID=1010
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /apps/configs/plexrequests:/config 

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    restart: always
    environment:
      - VERSION=latest
      - PUID=1010
      - PGID=1010
    volumes:
      - /apps/configs/plex:/config
      - /media/movies:/data/movies
      - /media/tv:/data/tvshows
  
  sonarr:
    image: linuxserver/sonarr:latest 
    container_name: sonarr
    ports:
      - "8989:8989"
      - "9898:9898"
    restart: always
    environment:
      - PGID=1010
      - PUID=1010
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - /apps/configs/sonarr:/config
      - /media/tv:/tv
      - /media/nzbget/downloads/completed/:/downloads

  couchpotato:
    image: linuxserver/couchpotato:latest 
    container_name: couchpotato
    ports:
      - "5050:5050"
    restart: always
    environment:
      - PGID=1010
      - PUID=1010
    volumes:
      - /apps/configs/couchpotato:/config
      - /media/movies:/movies
      - /media/nzbget/downloads/completed/:/downloads

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PGID=1010
      - PUID=1010
    ports:
      - "6789:6789"
    restart: always
    volumes:
      - /apps/configs/nzbget:/config
      - /media/nzbget:/downloads
    
