# docker-compose.yml
version: '2'

services:

  plexrequests:
    image: linuxserver/plexrequests
    env_file: ./ids.env
    container_name: plexrequests
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /apps/configs/plexrequests:/config 
    links:
      - couchpotato
      - sonarr
      - plex

  plex:
    image: linuxserver/plex
    env_file: ./ids.env
    container_name: plex
    network_mode: host
    restart: always
    environment:
      - VERSION=latest
    volumes:
      - /apps/configs/plex:/config
      - /media/movies:/data/movies
      - /media/tv:/data/tvshows
  
  sonarr:
    image: linuxserver/sonarr:latest 
    env_file: ./ids.env
    container_name: sonarr
    ports:
      - "8989:8989"
      - "9898:9898"
    restart: always
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - /apps/configs/sonarr:/config
      - /media/tv:/tv
      - /media/downloads/:/downloads
    links:
      - nzbget
      - deluge
      - plex

  couchpotato:
    image: linuxserver/couchpotato:latest 
    env_file: ./ids.env
    container_name: couchpotato
    ports:
      - "5050:5050"
    restart: always
    volumes:
      - /apps/configs/couchpotato:/config
      - /media/movies:/movies
      - /media/downloads/:/downloads
    links:
      - plex
      - nzbget
      - deluge

  nzbget:
    image: linuxserver/nzbget:latest
    env_file: ./ids.env
    container_name: nzbget
    ports:
      - "6789:6789"
    restart: always
    volumes:
      - /apps/configs/nzbget:/config
      - /media/downloads:/downloads
    
  deluge:
    image: linuxserver/deluge:latest
    env_file: ./ids.env
    container_name: deluge
    network_mode: host
    restart: always
    volumes:
      - /apps/configs/deluge:/config
      - /media/downloads:/downloads

  plexpy:
    image: linuxserver/plexpy:latest
    env_file: ./ids.env
    container_name: plexpy
    restart: always
    volumes:
      - /apps/configs/plexpy:/config
      - /apps/configs/plex/Library/Application\ Support/Plex\ Media\ Server/Logs/:/logs
    links:
      - plex
